apiVersion: mcp.k8s.io/v1alpha1
kind: MCPKubernetesServer
metadata:
  name: mcpoperator
  namespace: automationx
spec:
  namespaces:
    - automationx
  ingress:
    enabled: true
    host: mcpoperator.68.220.202.177.nip.io
    path: /mcp
    ingressClassName: nginx
    tls:
      enabled: true
      secretName: mcpoperator-tls
  auth:
    type: basic
    basic:
      secretName: mcpoperator-basic-auth
