apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-mcpoperator-server
  namespace: automationx
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - --dockerfile=/workspace/Dockerfile
            - --context=dir:///workspace
            - --destination=registry.68.220.202.177.nip.io/mcpoperator-python:latest
            - --insecure
            - --skip-tls-verify
