apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcpoperator
  namespace: automationx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mcpoperator.68.220.202.177.nip.io
      secretName: mcpoperator-tls
  rules:
    - host: mcpoperator.68.220.202.177.nip.io
      http:
        paths:
          - path: /mcp
            pathType: Prefix
            backend:
              service:
                name: mcp-server
                port:
                  number: 8080
